name: piconn
version: git
summary: Raspberry Pi's connection to things
description: |
  PiConn is a project that allows for remote control of
  the Raspberry Pi

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: armhf
    run-on: armhf

environment:
  PYTHONPATH: $PYTHONPATH:$SNAP_COMMON/crossbar-runtime-dir/lib/python3.6/site-packages

apps:
  gpio:
    command: cli.py
    plugs:
      - gpio
      - network
  piconnd:
    command: daemon.py
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
      - gpio

parts:
  launcher:
    plugin: dump
    source: .
    stage:
      - daemon.py
      - cli.py
    prime:
      - daemon.py
      - cli.py

plugs:
  deskconnd-sock-dir:
    content: socket-directory
    default-provider: deskconnd:sock-dir
    interface: content
    target: $SNAP_COMMON/deskconnd-sock-dir
  crossbar-runtime-dir:
    content: executables
    default-provider: crossbar:runtime-dir
    interface: content
    target: $SNAP_COMMON/deskconnd-runtime-dir
