name: gpiod
version: git
summary: Control your Rasbperry Pi's GPIO pins remotely, in real-time
description: |
  Control your Rasbperry Pi's GPIO pins remotely, in real-time

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: armhf
    run-on: armhf

apps:
  gpio:
    command: python3 -u $SNAP/pigpio.py
    plugs:
      - gpio
      - network
  gpiod:
    command: python3 -u $SNAP/pigpiod.py
    daemon: simple
    restart-condition: never
    plugs:
      - network
      - network-bind
      - gpio

parts:
  launcher:
    plugin: dump
    source: .
    prime:
      - pigpiod.py
      - pigpio.py
  pigpio:
    plugin: python
    source: .
    build-packages:
      - libffi-dev
      - libssl-dev
    python-packages:
      - autobahn[twisted,serialization]
      - requests
    override-prime: |
      snapcraftctl prime
      echo "Compiling pyc files..."
      $SNAPCRAFT_PART_INSTALL/usr/bin/python3 -m compileall -q $SNAPCRAFT_PRIME

plugs:
  deskconn-sock-dir:
    content: socket-directory
    default-provider: deskconnd:deskconn-sock-dir
    interface: content
    target: $SNAP_COMMON
