name: gpiod
version: git
summary: Control your Rasbperry Pi's GPIO pins remotely, in real-time
description: |
  Control your Rasbperry Pi's GPIO pins remotely, in real-time

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: armhf
    run-on: armhf

environment:
  PYTHONPATH: PYTHONPATH:$SNAP_COMMON/deskconnd-runtime-dir

apps:
  gpio:
    command: python3 -u $SNAP/pigpio.py
    plugs:
      - gpio
      - network
  gpiod:
    command: python3 -u $SNAP/pigpiod.py
    daemon: simple
    restart-condition: never
    plugs:
      - network
      - network-bind
      - gpio

parts:
  launcher:
    plugin: dump
    source: .
    prime:
      - pigpiod.py
      - pigpio.py
  pigpio:
    plugin: python
    source: .

plugs:
  deskconnd-sock-dir:
    content: socket-directory
    default-provider: deskconnd:sock-dir
    interface: content
    target: $SNAP_COMMON/deskconnd-sock-dir
  deskconnd-runtime-dir:
    content: executables
    default-provider: deskconnd:runtime-dir
    interface: content
    target: $SNAP_COMMON/deskconnd-runtime-dir
