name: pigpio
version: '0.1'
summary: TBD
description: |
  TBD

grade: devel
# Can't access GPIO path in strict confinement
# inquire from Ubuntu devs if its possible for a
# confined snap to talk to GPIO on the Raspberry Pi.
confinement: devmode

apps:
  pigpio:
    command: runner
    plugs: [network]
    environment:
      # FIXME: had to export this for our code to read
      # dependencies installed from requirement.txt.
      # This should not be needed, inquire Ubuntu guys
      # on why this is needed and a possible fix.
      PYTHONPATH: $SNAP/lib/python3.5/site-packages

parts:
  pigpio:
    plugin: python
    source: https://github.com/om26er/wamp-pigpio.git
    requirements: requirements.txt
  cli:
    plugin: dump
    source: .
    filesets:
      cli: [bin/runner]
    stage:
      - $cli
    organize:
      runner: bin/

hooks:
  configure:
    # We don't really need this BUT I didn't
    # find a way for 'configure' hook to
    # work without a sub item.
    plugs: [network]
