name: pigpio
version: git
summary: Control your Rasbperry Pi's GPIO pins remotely, in real-time
description: |
  Control your Rasbperry Pi's GPIO pins remotely, in real-time

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: armhf
    run-on: armhf

apps:
  pigpio:
    command: python3 -u $SNAP/pigpio.py
    plugs:
      - gpio
  pigpiod:
    command: python3 -u $SNAP/pigpiod.py
    daemon: simple
    restart-condition: never
    plugs:
      - network
      - network-bind
      - gpio

parts:
  launcher:
    plugin: dump
    source: .
    prime:
      - pigpiod.py
      - pigpio.py
  pigpio:
    plugin: python
    python-packages:
      - autobahn[twisted,serialization]

plugs:
  deskconn-sock-dir:
    interface: content
    content: socket-directory
    default-provider: deskconn:deskconn-sock-dir
    target: $SNAP_COMMON
