name: pigpio
version: '0.1'
summary: TBD
description: |
  TBD

grade: devel
confinement: devmode

apps:
  pigpio:
    command: runner.py
    plugs: [network]
    environment:
      PYTHONPATH: $SNAP/lib/python3.5/site-packages:$PYTHONPATH

parts:
  pigpio:
    plugin: python
    source: .
    requirements: requirements.txt
  cli:
    plugin: dump
    source: .
    filesets:
      cli: [bin/runner.py]
    stage:
      - $cli
    organize:
      runner.py: bin/

hooks:
  configure:
    plugs: []
