name: gpiod
version: git
summary: Control your Rasbperry Pi's GPIO pins remotely, in real-time
description: |
  Control your Rasbperry Pi's GPIO pins remotely, in real-time

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: armhf
    run-on: armhf

environment:
  PYTHONPATH: $PYTHONPATH:$SNAP_COMMON/deskconnd-runtime-dir

apps:
  gpio:
    command: cli.py
    plugs:
      - gpio
      - network
  gpiod:
    command: daemon.py
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
      - gpio

parts:
  launcher:
    plugin: dump
    source: .
    stage:
      - daemon.py
      - cli.py
    prime:
      - daemon.py
      - cli.py

plugs:
  deskconnd-sock-dir:
    content: socket-directory
    default-provider: deskconnd:sock-dir
    interface: content
    target: $SNAP_COMMON/deskconnd-sock-dir
  crossbar-runtime-dir:
    content: executables
    default-provider: crossbar:runtime-dir
    interface: content
    target: $SNAP_COMMON/deskconnd-runtime-dir
