name: pigpio
version: '0.2'
summary: Control your Rasbperry Pi's GPIO pins remotely, in real-time
description: |
  TBD

grade: stable
confinement: devmode

apps:
  pigpio:
    command: pigpio
#    daemon: simple
    plugs:
      - network

parts:
  pigpio:
    plugin: python
    source: .
    requirements: requirements.txt

#architectures:
#  - armhf
