name: pigpio
version: '0.3'
summary: Control your Rasbperry Pi's GPIO pins remotely, in real-time
description: |
  Control your Rasbperry Pi's GPIO pins remotely, in real-time

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: armhf
    run-on: armhf

apps:
  pigpio:
    command: python3 -u $SNAP/run.py
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
      - gpio

parts:
  scripts:
    plugin: dump
    source: .
    prime:
      - run.py
      - crossbar-config
  pigpio:
    plugin: python
    source: .
    requirements: requirements.txt
    build-packages:
      - libffi-dev
      - libssl-dev
