name: pigpio
version: '0.1'
summary: TBD
description: |
  TBD

grade: stable
# Can't access GPIO path in strict confinement
# inquire from Ubuntu devs if its possible for a
# confined snap to talk to GPIO on the Raspberry Pi.
confinement: devmode

apps:
  pigpio:
    command: pigpio
    daemon: simple
    plugs:
      - network

parts:
  pigpio:
    plugin: python
    source: .
    requirements: requirements.txt

architectures:
  - armhf
